[tool.poetry]
name = "HereIsMyVeryNiceProject"
version = "0.1.0"
description = "Test"
authors = ["Tommaso Comparin <3862206+tcompa@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.4.2"
bumpver = "^2023.1126"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
