name: Publish on TestPyPI
on: workflow_dispatch

jobs:
  Build and publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:

      - name: Check that PYPY_TOKEN secret exists
        env:
            CURRENT_PYPY_TOKEN: ${{ secrets.PYPY_TOKEN}}
        if: ${{ env.CURRENT_PYPY_TOKEN == '' }}
        run: echo "Secret PYPY_TOKEN is not defined." && exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.5

      - name: Build package
        run: poetry build --verbose

      - name: Publish to TestPyPI
        run: poetry publish --repository testpypi --username __token__ --password ${{ secrets.PYPY_TOKEN }}
