name: Publish on TestPyPI
on: workflow_dispatch

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      # - uses: actions/checkout@v4
      #- name: Build and publish to pypi
      #  uses: JRubics/poetry-publish@v1.17
      #  with:
      #    pypi_token: ${{ secrets.PYPI_TOKEN }}
      #    repository_name: "testpypi"
      #    repository_url: "https://test.pypi.org/legacy/"
      #    python_version: "3.10"
      #    poetry_version: "==1.5

      # - name: "Set up Python 3.10"
      #   uses: actions/setup-python@v4
      #   with:
      #    python-version: "3.10"
      #
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.5

      - name: Build package
        run: poetry build --verbose

      - name: Publish to TestPyPI
        run: \
          poetry source add testpypi https://test.pypi.org/legacy/ && \
          poetry publish --repository testpypi --username __token__ --password ${{ secrets.PYPI_TOKEN }}
